### ISSUE TITLE
Add new makedown cheetsheet post

### ISSUE THREAD

**Issue by anufdo** [CodeCommunityHub/epotha#6]
Add a new markdown file as a post including the following. Please use markdown syntax to style it and make a link to the main page.
Headers
Emphasis
Lists

- Unordered list
- Ordered list

Links
Images
Code

-   Inline code
-   Code block

Blockquotes
Horizontal rule
Tables
Task lists

**Comment by naveensanjula975** [comment]
Can you please assign me :)

**Comment by anufdo** [comment]
Yes. @naveensanjula975 you are now assigned

**Comment by anufdo** [comment]
Good job👍
