### ISSUE TITLE
Edit about.markdown

### ISSUE THREAD

**Issue by anufdo** [CodeCommunityHub/epotha#9]
Can you please update the about—markdown content for the flowing doc.  Please use markdown syntax to style it.

[Epotha.docx](https://github.com/CodeCommunityHub/epotha/files/11297340/Epotha.docx)

**Comment by ammarfitwalla** [comment]
Can I work on this as well?

**Comment by anufdo** [comment]
Yes, you can.

Create a new branch for your pull request. For example, you can name it 'Edit-about.markdown#9'. When you're working on it, make sure to change the status to 'In Progress'. Once you're finished and need a review, please change the status to 'Review in Progress'

**Comment by anufdo** [comment]
Good Job👍
